package com.ozguryazilim.telve.boot.labormarketidm.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "UserModel")
public class UserModel {
    private String id;
    private String username;
    private String password;
    private String email;
    private String phone;
    private String address;
    private String name;
    private String surname;
    private String birthDate;
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getUsername() {
        return username;
    }
    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }
    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }
    @DynamoDBAttribute
    public String getPhone() {
        return phone;
    }
    @DynamoDBAttribute
    public String getAddress() {
        return address;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }
    @DynamoDBAttribute
    public String getSurname() {
        return surname;
    }
    @DynamoDBAttribute
    public String getBirthDate() {
        return birthDate;
    }
}
